### ISSUE TITLE
Support for words with existing(full/partial) diacritics

### ISSUE THREAD

**Issue by Kentoseth** [AliOsm/shakkelha-website#2]
I've been testing shakkelha for a while and it is very accurate with diacritics(compared to other options), it is a really great piece of software!

One drawback is that certain texts with partial diacritics are overwritten with the ML. Here is a sample from an Oscar Wilde book:

> في موضعٍ عالٍ فوق المدينة، على عمود طويل، كان تمثال الأمير السعيد يقف منتصبًا، مطليًّا بالكامل برقائق الذهب الخالص، ووُضِع له حجرا زفير برَّاقان في موضع العينَين، بينما كانت تلمع على مقبض سيفه ياقوتة حمراء كبيرة.

and here is the output from shakkelha:

> فِي مَوْضِعٍ عَالٍ فَوْقَ الْمَدِينَةِ، عَلَى عَمُودٍ طَوِيلٍ، كَانَ تِمْثَالُ الأَمِيرِ السَّعِيدِ يَقِفُ مُنْتَصِبًا، مَطْلِيًّا بِالْكَامِلِ بِرَقَائِقِ الذَّهَبِ الْخَالِصِ، وَوَضَعَ لَهُ حَجْرًا زُفِيرٌ بُرَاقَانُ فِي مَوْضِعِ الْعَيْنَيْنِ، بَيْنَمَا كَانَتْ تَلْمَعُ عَلَى مُقْبِضِ سَيْفُهُ يَاقُوتَةً حَمْرَاءَ كَبِيرَةً.

The 2 places where it overwrites the diacritics and alters the meaning are:

> ووُضِع -> وَوَضَعَ

> برَّاقان -> بُرَاقَانُ

Is it possible to integrate some tooling that acknowledges the presence of partial diacritics and tries to find suitable matches based on what they are?

**Comment by AliOsm** [comment]
Hello @Kentoseth, thanks for your words.

About the issue you mentioned, this is completely right, the current model doesn't benefit from the partial diacritics. Also, the website doesn't support this.
As a fast solution, I can support replacing the partial diacritics with the predicted diacritics before publishing the final results.

Let me know what do you think please.

About the partial diacritizing thing, we did a lot of experiments about this topic but unfortunately we didn't publish anything until now.

**Comment by Kentoseth** [comment]
Salam,

Thank you for the quick reply!

> the current model doesn't benefit from the partial diacritics.

This is completely fine and understandable. Making this work in the model itself will be really difficult so I can understand why you chose not to implement it.

>  As a fast solution, I can support replacing the partial diacritics with the predicted diacritics before publishing the final results.

If my understanding of what you are saying is correct(it was a bit vague to me), you and I want to achieve the same thing. My thinking was the following:

1. If a word has >1 diacritic present(eg. برَّاقان ~ which has 2 if we include the shadda), then this is acknowledged by the app
2. After the diacritic addition is run by the app, the machine-generated diacritics are replaced by the acknowledged partial diacritics in 1. above
3. This is output as the result(preserving the partial diacritics)

My understanding of why authors add partial diacritics is to remove ambiguity. 

Another thing regarding partial diacritics is that instances where the diacritic is a fat7a and on the last letter, like: `منتصبًا، مطليًّا` Should possibly be ignored? My theory is that the model is already correctly predicting these, so preserving these instances is not necessary. What do you think?

(off-topic: I sent you an email to discuss your findings in your 2 research papers, but I am not sure if you received my email. Gmail has very aggressive spam filters, so it wouldn't surprise me if you didn't receive my email due to it)

**Comment by AliOsm** [comment]
> 1. If a word has >1 diacritic present(eg. برَّاقان ~ which has 2 if we include the shadda), then this is acknowledged by the app
> 2. After the diacritic addition is run by the app, the machine-generated diacritics are replaced by the acknowledged partial diacritics in 1. above
> 3. This is output as the result(preserving the partial diacritics)

This is exactly what I'm thinking about and it is easy to implement.
I'm just thinking about one thing. if the word in partially diacritized, do we really need to remove the predicted diacritics from the non-diacritized characters? As an example, if the word was `مَطلَب` and the model predicts `مُطْلَبْ`, we will use the partial diacritics for م and ل, but do we really need to drop the diacritics for ط and ب?

> Another thing regarding partial diacritics is that instances where the diacritic is a fat7a and on the last letter, like: منتصبًا، مطليًّا Should possibly be ignored? My theory is that the model is already correctly predicting these, so preserving these instances is not necessary. What do you think?

I would recommend to treat all partial diacritics in the same behavior. So, when there is a partial diacritics, simply we replace them with the predicted ones in the word. What do you think?

> (off-topic: I sent you an email to discuss your findings in your 2 research papers, but I am not sure if you received my email. Gmail has very aggressive spam filters, so it wouldn't surprise me if you didn't receive my email due to it)

To be honest, I found the email and I read it days ago but I forgot to reply. Sorry for that :').

**Comment by Kentoseth** [comment]
> do we really need to remove the predicted diacritics from the non-diacritized characters? As an example, if the word was مَطلَب and the model predicts مُطْلَبْ, we will use the partial diacritics for م and ل, but do we really need to drop the diacritics for ط and ب?

I didn't consider this and this is actually the best solution. This is definitely the better option to go with, that way the word gets full diacritics.

> I would recommend to treat all partial diacritics in the same behavior. So, when there is a partial diacritics, simply we replace them with the predicted ones in the word. What do you think?

I agree. We can use the solution you suggested above for all partial diacritics.

> To be honest, I found the email and I read it days ago but I forgot to reply. Sorry for that :').

No problem. I really liked your research and read both papers. It is cutting edge and I hope to use shakkelha to expand its usage.

**Comment by AliOsm** [comment]
Then, I will try to do a PR on this change and we can discuss it there.

**Comment by AliOsm** [comment]
@Kentoseth Can you review please: https://github.com/AliOsm/shakkelha-website/pull/4

**Comment by AliOsm** [comment]
The PR merged successfully, deploying the change to Heroku...

**Comment by AliOsm** [comment]
Deployed, I will close this issue.
