### ISSUE TITLE
Python library issue - h5py

### ISSUE THREAD

**Issue by Kentoseth** [AliOsm/shakkelha-website#3]
Hi,

I just remembered that the website app also has a bug regarding: h5py 3.1.0

If you use h5py 3.1.0 and try to run the Flask app, a bug appears:

> AttributeError: 'str' object has no attribute 'decode'

This is documented here: https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi

The solution is to do the following:

`pip install 'h5py==2.10.0' --force-reinstall`

then it works.

**Comment by AliOsm** [comment]
I tried this locally using Python 3.6 and installed all packages using `pip install -r requirements.txt` and the error didn't happen with me.

**Comment by Kentoseth** [comment]
I am documenting this for Python3.7, which is where the error was. We can close this issue(or if you prefer I can make a PR to the README file mentioning it).

**Comment by AliOsm** [comment]
This is totally fine, you can create the PR.
